/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ErasmusProgramsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ErasmusProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.ErasmusProgram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cErasmusProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTotalCreditsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTotalCreditsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTotalCreditsINTTerminalRuleCall_4_0 = (RuleCall)cTotalCreditsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUniversitiesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cUniversitiesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cUniversitiesUniversityParserRuleCall_5_2_0 = (RuleCall)cUniversitiesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cUniversitiesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cUniversitiesUniversityParserRuleCall_5_3_1_0 = (RuleCall)cUniversitiesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cScholarshipsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cScholarshipsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cScholarshipsScholarshipParserRuleCall_6_2_0 = (RuleCall)cScholarshipsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cScholarshipsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cScholarshipsScholarshipParserRuleCall_6_3_1_0 = (RuleCall)cScholarshipsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAssociatePartnersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAssociatePartnersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAssociatePartnersAssociatePartnerParserRuleCall_7_2_0 = (RuleCall)cAssociatePartnersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAssociatePartnersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAssociatePartnersAssociatePartnerParserRuleCall_7_3_1_0 = (RuleCall)cAssociatePartnersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cAdmissionStructureKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cAdmissionStructureAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cAdmissionStructureAdmissionStructureParserRuleCall_9_0 = (RuleCall)cAdmissionStructureAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		////generate erasmusPrograms "http://www.xtext.org/mde/a5/ErasmusPrograms"
		//ErasmusProgram returns ErasmusProgram:
		//  'ErasmusProgram' name=STRING '{'
		//    'totalCredits' totalCredits=INT
		//    ('universities' '{' universities+=University (',' universities+=University)* '}' )?
		//    ('scholarships' '{' scholarships+=Scholarship (',' scholarships+=Scholarship)* '}' )?
		//    ('associatePartners' '{' associatePartners+=AssociatePartner (',' associatePartners+=AssociatePartner)* '}' )?
		//    'admissionStructure' admissionStructure=AdmissionStructure
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ErasmusProgram' name=STRING '{'
		//  'totalCredits' totalCredits=INT
		//  ('universities' '{' universities+=University (',' universities+=University)* '}' )?
		//  ('scholarships' '{' scholarships+=Scholarship (',' scholarships+=Scholarship)* '}' )?
		//  ('associatePartners' '{' associatePartners+=AssociatePartner (',' associatePartners+=AssociatePartner)* '}' )?
		//  'admissionStructure' admissionStructure=AdmissionStructure
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ErasmusProgram'
		public Keyword getErasmusProgramKeyword_0() { return cErasmusProgramKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'totalCredits'
		public Keyword getTotalCreditsKeyword_3() { return cTotalCreditsKeyword_3; }
		
		//totalCredits=INT
		public Assignment getTotalCreditsAssignment_4() { return cTotalCreditsAssignment_4; }
		
		//INT
		public RuleCall getTotalCreditsINTTerminalRuleCall_4_0() { return cTotalCreditsINTTerminalRuleCall_4_0; }
		
		//('universities' '{' universities+=University (',' universities+=University)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'universities'
		public Keyword getUniversitiesKeyword_5_0() { return cUniversitiesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//universities+=University
		public Assignment getUniversitiesAssignment_5_2() { return cUniversitiesAssignment_5_2; }
		
		//University
		public RuleCall getUniversitiesUniversityParserRuleCall_5_2_0() { return cUniversitiesUniversityParserRuleCall_5_2_0; }
		
		//(',' universities+=University)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//universities+=University
		public Assignment getUniversitiesAssignment_5_3_1() { return cUniversitiesAssignment_5_3_1; }
		
		//University
		public RuleCall getUniversitiesUniversityParserRuleCall_5_3_1_0() { return cUniversitiesUniversityParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('scholarships' '{' scholarships+=Scholarship (',' scholarships+=Scholarship)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'scholarships'
		public Keyword getScholarshipsKeyword_6_0() { return cScholarshipsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//scholarships+=Scholarship
		public Assignment getScholarshipsAssignment_6_2() { return cScholarshipsAssignment_6_2; }
		
		//Scholarship
		public RuleCall getScholarshipsScholarshipParserRuleCall_6_2_0() { return cScholarshipsScholarshipParserRuleCall_6_2_0; }
		
		//(',' scholarships+=Scholarship)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//','
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//scholarships+=Scholarship
		public Assignment getScholarshipsAssignment_6_3_1() { return cScholarshipsAssignment_6_3_1; }
		
		//Scholarship
		public RuleCall getScholarshipsScholarshipParserRuleCall_6_3_1_0() { return cScholarshipsScholarshipParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('associatePartners' '{' associatePartners+=AssociatePartner (',' associatePartners+=AssociatePartner)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'associatePartners'
		public Keyword getAssociatePartnersKeyword_7_0() { return cAssociatePartnersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//associatePartners+=AssociatePartner
		public Assignment getAssociatePartnersAssignment_7_2() { return cAssociatePartnersAssignment_7_2; }
		
		//AssociatePartner
		public RuleCall getAssociatePartnersAssociatePartnerParserRuleCall_7_2_0() { return cAssociatePartnersAssociatePartnerParserRuleCall_7_2_0; }
		
		//(',' associatePartners+=AssociatePartner)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//','
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//associatePartners+=AssociatePartner
		public Assignment getAssociatePartnersAssignment_7_3_1() { return cAssociatePartnersAssignment_7_3_1; }
		
		//AssociatePartner
		public RuleCall getAssociatePartnersAssociatePartnerParserRuleCall_7_3_1_0() { return cAssociatePartnersAssociatePartnerParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'admissionStructure'
		public Keyword getAdmissionStructureKeyword_8() { return cAdmissionStructureKeyword_8; }
		
		//admissionStructure=AdmissionStructure
		public Assignment getAdmissionStructureAssignment_9() { return cAdmissionStructureAssignment_9; }
		
		//AdmissionStructure
		public RuleCall getAdmissionStructureAdmissionStructureParserRuleCall_9_0() { return cAdmissionStructureAdmissionStructureParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class ScholarshipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Scholarship");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeScholarshipTypeEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTuitionFeeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTuitionFeeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTuitionFeeINTTerminalRuleCall_3_0 = (RuleCall)cTuitionFeeAssignment_3.eContents().get(0);
		private final Keyword cTravelGrantKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTravelGrantAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTravelGrantINTTerminalRuleCall_5_0 = (RuleCall)cTravelGrantAssignment_5.eContents().get(0);
		private final Keyword cAllowanceKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAllowanceAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAllowanceINTTerminalRuleCall_7_0 = (RuleCall)cAllowanceAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Scholarship returns Scholarship:
		//  type=ScholarshipType '{'
		//    'tuitionFee' tuitionFee=INT
		//    'travelGrant' travelGrant=INT
		//    'allowance' allowance=INT
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//type=ScholarshipType '{'
		//  'tuitionFee' tuitionFee=INT
		//  'travelGrant' travelGrant=INT
		//  'allowance' allowance=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//type=ScholarshipType
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//ScholarshipType
		public RuleCall getTypeScholarshipTypeEnumRuleCall_0_0() { return cTypeScholarshipTypeEnumRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'tuitionFee'
		public Keyword getTuitionFeeKeyword_2() { return cTuitionFeeKeyword_2; }
		
		//tuitionFee=INT
		public Assignment getTuitionFeeAssignment_3() { return cTuitionFeeAssignment_3; }
		
		//INT
		public RuleCall getTuitionFeeINTTerminalRuleCall_3_0() { return cTuitionFeeINTTerminalRuleCall_3_0; }
		
		//'travelGrant'
		public Keyword getTravelGrantKeyword_4() { return cTravelGrantKeyword_4; }
		
		//travelGrant=INT
		public Assignment getTravelGrantAssignment_5() { return cTravelGrantAssignment_5; }
		
		//INT
		public RuleCall getTravelGrantINTTerminalRuleCall_5_0() { return cTravelGrantINTTerminalRuleCall_5_0; }
		
		//'allowance'
		public Keyword getAllowanceKeyword_6() { return cAllowanceKeyword_6; }
		
		//allowance=INT
		public Assignment getAllowanceAssignment_7() { return cAllowanceAssignment_7; }
		
		//INT
		public RuleCall getAllowanceINTTerminalRuleCall_7_0() { return cAllowanceINTTerminalRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class UniversityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.University");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUniversityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUniversityNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUniversityNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cUniversityNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLocationKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLocationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLocationLocationParserRuleCall_4_0 = (RuleCall)cLocationAssignment_4.eContents().get(0);
		private final Keyword cCreditsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCreditsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCreditsINTTerminalRuleCall_6_0 = (RuleCall)cCreditsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCoursesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cCoursesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cCoursesCourseParserRuleCall_7_2_0 = (RuleCall)cCoursesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cCoursesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cCoursesCourseParserRuleCall_7_3_1_0 = (RuleCall)cCoursesAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//University returns University:
		//  'University' universityName=STRING '{'
		//    'location' location=Location
		//    'credits' credits=INT
		//    ('courses' '{' courses+=Course (',' courses+=Course)* '}' )?
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'University' universityName=STRING '{'
		//  'location' location=Location
		//  'credits' credits=INT
		//  ('courses' '{' courses+=Course (',' courses+=Course)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'University'
		public Keyword getUniversityKeyword_0() { return cUniversityKeyword_0; }
		
		//universityName=STRING
		public Assignment getUniversityNameAssignment_1() { return cUniversityNameAssignment_1; }
		
		//STRING
		public RuleCall getUniversityNameSTRINGTerminalRuleCall_1_0() { return cUniversityNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'location'
		public Keyword getLocationKeyword_3() { return cLocationKeyword_3; }
		
		//location=Location
		public Assignment getLocationAssignment_4() { return cLocationAssignment_4; }
		
		//Location
		public RuleCall getLocationLocationParserRuleCall_4_0() { return cLocationLocationParserRuleCall_4_0; }
		
		//'credits'
		public Keyword getCreditsKeyword_5() { return cCreditsKeyword_5; }
		
		//credits=INT
		public Assignment getCreditsAssignment_6() { return cCreditsAssignment_6; }
		
		//INT
		public RuleCall getCreditsINTTerminalRuleCall_6_0() { return cCreditsINTTerminalRuleCall_6_0; }
		
		//('courses' '{' courses+=Course (',' courses+=Course)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'courses'
		public Keyword getCoursesKeyword_7_0() { return cCoursesKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//courses+=Course
		public Assignment getCoursesAssignment_7_2() { return cCoursesAssignment_7_2; }
		
		//Course
		public RuleCall getCoursesCourseParserRuleCall_7_2_0() { return cCoursesCourseParserRuleCall_7_2_0; }
		
		//(',' courses+=Course)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//','
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//courses+=Course
		public Assignment getCoursesAssignment_7_3_1() { return cCoursesAssignment_7_3_1; }
		
		//Course
		public RuleCall getCoursesCourseParserRuleCall_7_3_1_0() { return cCoursesCourseParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCourseCodeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCourseCodeSTRINGTerminalRuleCall_3_0 = (RuleCall)cCourseCodeAssignment_3.eContents().get(0);
		private final Keyword cNameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCourseNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCourseNameSTRINGTerminalRuleCall_6_0 = (RuleCall)cCourseNameAssignment_6.eContents().get(0);
		private final Keyword cFacultyKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cColonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFacultyAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFacultySTRINGTerminalRuleCall_9_0 = (RuleCall)cFacultyAssignment_9.eContents().get(0);
		private final Keyword cCreditsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cColonKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cCourseCreditsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cCourseCreditsINTTerminalRuleCall_12_0 = (RuleCall)cCourseCreditsAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Course returns Course:
		//  '{'
		//    'code' ':' courseCode=STRING
		//    'name' ':' courseName=STRING
		//    'faculty' ':' faculty=STRING
		//    'credits' ':' courseCredits=INT
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//  'code' ':' courseCode=STRING
		//  'name' ':' courseName=STRING
		//  'faculty' ':' faculty=STRING
		//  'credits' ':' courseCredits=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'code'
		public Keyword getCodeKeyword_1() { return cCodeKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//courseCode=STRING
		public Assignment getCourseCodeAssignment_3() { return cCourseCodeAssignment_3; }
		
		//STRING
		public RuleCall getCourseCodeSTRINGTerminalRuleCall_3_0() { return cCourseCodeSTRINGTerminalRuleCall_3_0; }
		
		//'name'
		public Keyword getNameKeyword_4() { return cNameKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//courseName=STRING
		public Assignment getCourseNameAssignment_6() { return cCourseNameAssignment_6; }
		
		//STRING
		public RuleCall getCourseNameSTRINGTerminalRuleCall_6_0() { return cCourseNameSTRINGTerminalRuleCall_6_0; }
		
		//'faculty'
		public Keyword getFacultyKeyword_7() { return cFacultyKeyword_7; }
		
		//':'
		public Keyword getColonKeyword_8() { return cColonKeyword_8; }
		
		//faculty=STRING
		public Assignment getFacultyAssignment_9() { return cFacultyAssignment_9; }
		
		//STRING
		public RuleCall getFacultySTRINGTerminalRuleCall_9_0() { return cFacultySTRINGTerminalRuleCall_9_0; }
		
		//'credits'
		public Keyword getCreditsKeyword_10() { return cCreditsKeyword_10; }
		
		//':'
		public Keyword getColonKeyword_11() { return cColonKeyword_11; }
		
		//courseCredits=INT
		public Assignment getCourseCreditsAssignment_12() { return cCourseCreditsAssignment_12; }
		
		//INT
		public RuleCall getCourseCreditsINTTerminalRuleCall_12_0() { return cCourseCreditsINTTerminalRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCountryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCountryNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCountryNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cCountryNameAssignment_3.eContents().get(0);
		private final Keyword cCityKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCityNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCityNameSTRINGTerminalRuleCall_6_0 = (RuleCall)cCityNameAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Location returns Location:
		//  '{'
		//    'country' ':' countryName=STRING
		//    'city' ':' cityName=STRING
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//  'country' ':' countryName=STRING
		//  'city' ':' cityName=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'country'
		public Keyword getCountryKeyword_1() { return cCountryKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//countryName=STRING
		public Assignment getCountryNameAssignment_3() { return cCountryNameAssignment_3; }
		
		//STRING
		public RuleCall getCountryNameSTRINGTerminalRuleCall_3_0() { return cCountryNameSTRINGTerminalRuleCall_3_0; }
		
		//'city'
		public Keyword getCityKeyword_4() { return cCityKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//cityName=STRING
		public Assignment getCityNameAssignment_6() { return cCityNameAssignment_6; }
		
		//STRING
		public RuleCall getCityNameSTRINGTerminalRuleCall_6_0() { return cCityNameSTRINGTerminalRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class AssociatePartnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.AssociatePartner");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPartnerNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPartnerNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cPartnerNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypePartnerTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AssociatePartner returns AssociatePartner:
		//    partnerName=STRING '(' type=PartnerType ')';
		@Override public ParserRule getRule() { return rule; }
		
		//partnerName=STRING '(' type=PartnerType ')'
		public Group getGroup() { return cGroup; }
		
		//partnerName=STRING
		public Assignment getPartnerNameAssignment_0() { return cPartnerNameAssignment_0; }
		
		//STRING
		public RuleCall getPartnerNameSTRINGTerminalRuleCall_0_0() { return cPartnerNameSTRINGTerminalRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//type=PartnerType
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//PartnerType
		public RuleCall getTypePartnerTypeEnumRuleCall_2_0() { return cTypePartnerTypeEnumRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class AdmissionStructureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.AdmissionStructure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cApplicationProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cApplicationProcessAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cApplicationProcessApplicationProcessParserRuleCall_2_0 = (RuleCall)cApplicationProcessAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRequirementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRequierementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cRequierementsRequirementParserRuleCall_3_2_0 = (RuleCall)cRequierementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRequierementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cRequierementsRequirementParserRuleCall_3_3_1_0 = (RuleCall)cRequierementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResultsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cResultsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cResultsResultsParserRuleCall_4_2_0 = (RuleCall)cResultsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cResultsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cResultsResultsParserRuleCall_4_3_1_0 = (RuleCall)cResultsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//AdmissionStructure returns AdmissionStructure:
		//  '{'
		//    'applicationProcess' applicationProcess=ApplicationProcess
		//    ('requirements' '{' requierements+=Requirement (',' requierements+=Requirement)* '}' )?
		//    ('results' '{' results+=Results (',' results+=Results)* '}' )?
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{'
		//  'applicationProcess' applicationProcess=ApplicationProcess
		//  ('requirements' '{' requierements+=Requirement (',' requierements+=Requirement)* '}' )?
		//  ('results' '{' results+=Results (',' results+=Results)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'applicationProcess'
		public Keyword getApplicationProcessKeyword_1() { return cApplicationProcessKeyword_1; }
		
		//applicationProcess=ApplicationProcess
		public Assignment getApplicationProcessAssignment_2() { return cApplicationProcessAssignment_2; }
		
		//ApplicationProcess
		public RuleCall getApplicationProcessApplicationProcessParserRuleCall_2_0() { return cApplicationProcessApplicationProcessParserRuleCall_2_0; }
		
		//('requirements' '{' requierements+=Requirement (',' requierements+=Requirement)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'requirements'
		public Keyword getRequirementsKeyword_3_0() { return cRequirementsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//requierements+=Requirement
		public Assignment getRequierementsAssignment_3_2() { return cRequierementsAssignment_3_2; }
		
		//Requirement
		public RuleCall getRequierementsRequirementParserRuleCall_3_2_0() { return cRequierementsRequirementParserRuleCall_3_2_0; }
		
		//(',' requierements+=Requirement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//','
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//requierements+=Requirement
		public Assignment getRequierementsAssignment_3_3_1() { return cRequierementsAssignment_3_3_1; }
		
		//Requirement
		public RuleCall getRequierementsRequirementParserRuleCall_3_3_1_0() { return cRequierementsRequirementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('results' '{' results+=Results (',' results+=Results)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'results'
		public Keyword getResultsKeyword_4_0() { return cResultsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//results+=Results
		public Assignment getResultsAssignment_4_2() { return cResultsAssignment_4_2; }
		
		//Results
		public RuleCall getResultsResultsParserRuleCall_4_2_0() { return cResultsResultsParserRuleCall_4_2_0; }
		
		//(',' results+=Results)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//','
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//results+=Results
		public Assignment getResultsAssignment_4_3_1() { return cResultsAssignment_4_3_1; }
		
		//Results
		public RuleCall getResultsResultsParserRuleCall_4_3_1_0() { return cResultsResultsParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ResultsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Results");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cYearKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cYearAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cYearINTTerminalRuleCall_1_0 = (RuleCall)cYearAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTotalAdmittedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTotalAdmittedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTotalAdmittedINTTerminalRuleCall_4_0 = (RuleCall)cTotalAdmittedAssignment_4.eContents().get(0);
		private final Keyword cScholarshipsAwardedKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cScholarshipsAwardedAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cScholarshipsAwardedINTTerminalRuleCall_6_0 = (RuleCall)cScholarshipsAwardedAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAdmittedStudentsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAdmittedStudentsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAdmittedStudentsSTRINGTerminalRuleCall_7_2_0 = (RuleCall)cAdmittedStudentsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAdmittedStudentsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAdmittedStudentsSTRINGTerminalRuleCall_7_3_1_0 = (RuleCall)cAdmittedStudentsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Results returns Results:
		//  'Year' year=INT '{'
		//    'totalAdmitted' totalAdmitted=INT
		//    'scholarshipsAwarded' scholarshipsAwarded=INT
		//    ('admittedStudents' '{' admittedStudents+=STRING (',' admittedStudents+=STRING)* '}' )?
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Year' year=INT '{'
		//  'totalAdmitted' totalAdmitted=INT
		//  'scholarshipsAwarded' scholarshipsAwarded=INT
		//  ('admittedStudents' '{' admittedStudents+=STRING (',' admittedStudents+=STRING)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Year'
		public Keyword getYearKeyword_0() { return cYearKeyword_0; }
		
		//year=INT
		public Assignment getYearAssignment_1() { return cYearAssignment_1; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_1_0() { return cYearINTTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'totalAdmitted'
		public Keyword getTotalAdmittedKeyword_3() { return cTotalAdmittedKeyword_3; }
		
		//totalAdmitted=INT
		public Assignment getTotalAdmittedAssignment_4() { return cTotalAdmittedAssignment_4; }
		
		//INT
		public RuleCall getTotalAdmittedINTTerminalRuleCall_4_0() { return cTotalAdmittedINTTerminalRuleCall_4_0; }
		
		//'scholarshipsAwarded'
		public Keyword getScholarshipsAwardedKeyword_5() { return cScholarshipsAwardedKeyword_5; }
		
		//scholarshipsAwarded=INT
		public Assignment getScholarshipsAwardedAssignment_6() { return cScholarshipsAwardedAssignment_6; }
		
		//INT
		public RuleCall getScholarshipsAwardedINTTerminalRuleCall_6_0() { return cScholarshipsAwardedINTTerminalRuleCall_6_0; }
		
		//('admittedStudents' '{' admittedStudents+=STRING (',' admittedStudents+=STRING)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'admittedStudents'
		public Keyword getAdmittedStudentsKeyword_7_0() { return cAdmittedStudentsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//admittedStudents+=STRING
		public Assignment getAdmittedStudentsAssignment_7_2() { return cAdmittedStudentsAssignment_7_2; }
		
		//STRING
		public RuleCall getAdmittedStudentsSTRINGTerminalRuleCall_7_2_0() { return cAdmittedStudentsSTRINGTerminalRuleCall_7_2_0; }
		
		//(',' admittedStudents+=STRING)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//','
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//admittedStudents+=STRING
		public Assignment getAdmittedStudentsAssignment_7_3_1() { return cAdmittedStudentsAssignment_7_3_1; }
		
		//STRING
		public RuleCall getAdmittedStudentsSTRINGTerminalRuleCall_7_3_1_0() { return cAdmittedStudentsSTRINGTerminalRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Requirement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDocumentRequirementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDegreeRequirementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLanguageRequirementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Requirement returns Requirement:
		//  DocumentRequirement | DegreeRequirement | LanguageRequirement;
		@Override public ParserRule getRule() { return rule; }
		
		//DocumentRequirement | DegreeRequirement | LanguageRequirement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DocumentRequirement
		public RuleCall getDocumentRequirementParserRuleCall_0() { return cDocumentRequirementParserRuleCall_0; }
		
		//DegreeRequirement
		public RuleCall getDegreeRequirementParserRuleCall_1() { return cDegreeRequirementParserRuleCall_1; }
		
		//LanguageRequirement
		public RuleCall getLanguageRequirementParserRuleCall_2() { return cLanguageRequirementParserRuleCall_2; }
	}
	public class DocumentRequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.DocumentRequirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDocumentRequirementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDocumentNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDocumentNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDocumentNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cDocumentNameAssignment_3.eContents().get(0);
		private final Keyword cDescriptionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDescriptionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_0 = (RuleCall)cDescriptionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DocumentRequirement returns DocumentRequirement:
		//  'DocumentRequirement' '{'
		//    'documentName' documentName=STRING
		//    'description' description=STRING
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'DocumentRequirement' '{'
		//  'documentName' documentName=STRING
		//  'description' description=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'DocumentRequirement'
		public Keyword getDocumentRequirementKeyword_0() { return cDocumentRequirementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'documentName'
		public Keyword getDocumentNameKeyword_2() { return cDocumentNameKeyword_2; }
		
		//documentName=STRING
		public Assignment getDocumentNameAssignment_3() { return cDocumentNameAssignment_3; }
		
		//STRING
		public RuleCall getDocumentNameSTRINGTerminalRuleCall_3_0() { return cDocumentNameSTRINGTerminalRuleCall_3_0; }
		
		//'description'
		public Keyword getDescriptionKeyword_4() { return cDescriptionKeyword_4; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_5() { return cDescriptionAssignment_5; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_0() { return cDescriptionSTRINGTerminalRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DegreeRequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.DegreeRequirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDegreeRequirementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDegreeNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDegreeNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDegreeNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cDegreeNameAssignment_3.eContents().get(0);
		private final Keyword cFieldOfStudyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFieldOfStudyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFieldOfStudySTRINGTerminalRuleCall_5_0 = (RuleCall)cFieldOfStudyAssignment_5.eContents().get(0);
		private final Keyword cLevelKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLevelAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLevelDegreeLevelEnumRuleCall_7_0 = (RuleCall)cLevelAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//DegreeRequirement returns DegreeRequirement:
		//  'DegreeRequirement' '{'
		//    'degreeName' degreeName=STRING
		//    'fieldOfStudy' fieldOfStudy=STRING
		//    'level' level=DegreeLevel
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'DegreeRequirement' '{'
		//  'degreeName' degreeName=STRING
		//  'fieldOfStudy' fieldOfStudy=STRING
		//  'level' level=DegreeLevel
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'DegreeRequirement'
		public Keyword getDegreeRequirementKeyword_0() { return cDegreeRequirementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'degreeName'
		public Keyword getDegreeNameKeyword_2() { return cDegreeNameKeyword_2; }
		
		//degreeName=STRING
		public Assignment getDegreeNameAssignment_3() { return cDegreeNameAssignment_3; }
		
		//STRING
		public RuleCall getDegreeNameSTRINGTerminalRuleCall_3_0() { return cDegreeNameSTRINGTerminalRuleCall_3_0; }
		
		//'fieldOfStudy'
		public Keyword getFieldOfStudyKeyword_4() { return cFieldOfStudyKeyword_4; }
		
		//fieldOfStudy=STRING
		public Assignment getFieldOfStudyAssignment_5() { return cFieldOfStudyAssignment_5; }
		
		//STRING
		public RuleCall getFieldOfStudySTRINGTerminalRuleCall_5_0() { return cFieldOfStudySTRINGTerminalRuleCall_5_0; }
		
		//'level'
		public Keyword getLevelKeyword_6() { return cLevelKeyword_6; }
		
		//level=DegreeLevel
		public Assignment getLevelAssignment_7() { return cLevelAssignment_7; }
		
		//DegreeLevel
		public RuleCall getLevelDegreeLevelEnumRuleCall_7_0() { return cLevelDegreeLevelEnumRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class LanguageRequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.LanguageRequirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLanguageRequirementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLanguageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLanguageNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLanguageNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cLanguageNameAssignment_3.eContents().get(0);
		private final Keyword cLevelKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLevelAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLevelLanguageLevelEnumRuleCall_5_0 = (RuleCall)cLevelAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//LanguageRequirement returns LanguageRequirement:
		//  'LanguageRequirement' '{'
		//    'language' languageName=STRING
		//    'level' level=LanguageLevel
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'LanguageRequirement' '{'
		//  'language' languageName=STRING
		//  'level' level=LanguageLevel
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'LanguageRequirement'
		public Keyword getLanguageRequirementKeyword_0() { return cLanguageRequirementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'language'
		public Keyword getLanguageKeyword_2() { return cLanguageKeyword_2; }
		
		//languageName=STRING
		public Assignment getLanguageNameAssignment_3() { return cLanguageNameAssignment_3; }
		
		//STRING
		public RuleCall getLanguageNameSTRINGTerminalRuleCall_3_0() { return cLanguageNameSTRINGTerminalRuleCall_3_0; }
		
		//'level'
		public Keyword getLevelKeyword_4() { return cLevelKeyword_4; }
		
		//level=LanguageLevel
		public Assignment getLevelAssignment_5() { return cLevelAssignment_5; }
		
		//LanguageLevel
		public RuleCall getLevelLanguageLevelEnumRuleCall_5_0() { return cLevelLanguageLevelEnumRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ApplicationProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.ApplicationProcess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApplicationProcessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cStepsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cStepsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cStepsStepParserRuleCall_2_2_0 = (RuleCall)cStepsAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cStepsAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cStepsStepParserRuleCall_2_3_1_0 = (RuleCall)cStepsAssignment_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ApplicationProcess returns ApplicationProcess:
		//  {ApplicationProcess} '{'
		//    ('steps' '{' steps+=Step (',' steps+=Step)* '}' )?
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ApplicationProcess} '{'
		//  ('steps' '{' steps+=Step (',' steps+=Step)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ApplicationProcess}
		public Action getApplicationProcessAction_0() { return cApplicationProcessAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('steps' '{' steps+=Step (',' steps+=Step)* '}' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'steps'
		public Keyword getStepsKeyword_2_0() { return cStepsKeyword_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }
		
		//steps+=Step
		public Assignment getStepsAssignment_2_2() { return cStepsAssignment_2_2; }
		
		//Step
		public RuleCall getStepsStepParserRuleCall_2_2_0() { return cStepsStepParserRuleCall_2_2_0; }
		
		//(',' steps+=Step)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//','
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//steps+=Step
		public Assignment getStepsAssignment_2_3_1() { return cStepsAssignment_2_3_1; }
		
		//Step
		public RuleCall getStepsStepParserRuleCall_2_3_1_0() { return cStepsStepParserRuleCall_2_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class StepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.Step");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStepKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStepNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStepNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cStepNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDescriptionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStepDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStepDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cStepDescriptionAssignment_4.eContents().get(0);
		private final Keyword cStartDateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStartDateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStartDateEDATETerminalRuleCall_6_0 = (RuleCall)cStartDateAssignment_6.eContents().get(0);
		private final Keyword cEndDateKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEndDateAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEndDateEDATETerminalRuleCall_8_0 = (RuleCall)cEndDateAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Step returns Step:
		//  'Step' stepName=STRING '{'
		//    'description' stepDescription=STRING
		//    'startDate' startDate=EDATE
		//    'endDate' endDate=EDATE
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Step' stepName=STRING '{'
		//  'description' stepDescription=STRING
		//  'startDate' startDate=EDATE
		//  'endDate' endDate=EDATE
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Step'
		public Keyword getStepKeyword_0() { return cStepKeyword_0; }
		
		//stepName=STRING
		public Assignment getStepNameAssignment_1() { return cStepNameAssignment_1; }
		
		//STRING
		public RuleCall getStepNameSTRINGTerminalRuleCall_1_0() { return cStepNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'description'
		public Keyword getDescriptionKeyword_3() { return cDescriptionKeyword_3; }
		
		//stepDescription=STRING
		public Assignment getStepDescriptionAssignment_4() { return cStepDescriptionAssignment_4; }
		
		//STRING
		public RuleCall getStepDescriptionSTRINGTerminalRuleCall_4_0() { return cStepDescriptionSTRINGTerminalRuleCall_4_0; }
		
		//'startDate'
		public Keyword getStartDateKeyword_5() { return cStartDateKeyword_5; }
		
		//startDate=EDATE
		public Assignment getStartDateAssignment_6() { return cStartDateAssignment_6; }
		
		//EDATE
		public RuleCall getStartDateEDATETerminalRuleCall_6_0() { return cStartDateEDATETerminalRuleCall_6_0; }
		
		//'endDate'
		public Keyword getEndDateKeyword_7() { return cEndDateKeyword_7; }
		
		//endDate=EDATE
		public Assignment getEndDateAssignment_8() { return cEndDateAssignment_8; }
		
		//EDATE
		public RuleCall getEndDateEDATETerminalRuleCall_8_0() { return cEndDateEDATETerminalRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	public class ScholarshipTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.ScholarshipType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cProgram_CountryEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cProgram_CountryProgram_CountryKeyword_0_0 = (Keyword)cProgram_CountryEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPartner_CountryEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPartner_CountryPartner_CountryKeyword_1_0 = (Keyword)cPartner_CountryEnumLiteralDeclaration_1.eContents().get(0);
		
		//// Enums
		//enum ScholarshipType returns ScholarshipType:
		//  Program_Country | Partner_Country;
		public EnumRule getRule() { return rule; }
		
		//Program_Country | Partner_Country
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Program_Country
		public EnumLiteralDeclaration getProgram_CountryEnumLiteralDeclaration_0() { return cProgram_CountryEnumLiteralDeclaration_0; }
		
		public Keyword getProgram_CountryProgram_CountryKeyword_0_0() { return cProgram_CountryProgram_CountryKeyword_0_0; }
		
		//Partner_Country
		public EnumLiteralDeclaration getPartner_CountryEnumLiteralDeclaration_1() { return cPartner_CountryEnumLiteralDeclaration_1; }
		
		public Keyword getPartner_CountryPartner_CountryKeyword_1_0() { return cPartner_CountryPartner_CountryKeyword_1_0; }
	}
	public class LanguageLevelElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.LanguageLevel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cA1EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cA1A1Keyword_0_0 = (Keyword)cA1EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cA2EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cA2A2Keyword_1_0 = (Keyword)cA2EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cB1EnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cB1B1Keyword_2_0 = (Keyword)cB1EnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cB2EnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cB2B2Keyword_3_0 = (Keyword)cB2EnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cC1EnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cC1C1Keyword_4_0 = (Keyword)cC1EnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cC2EnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cC2C2Keyword_5_0 = (Keyword)cC2EnumLiteralDeclaration_5.eContents().get(0);
		
		//enum LanguageLevel returns LanguageLevel:
		//  A1 | A2 | B1 | B2 | C1 | C2;
		public EnumRule getRule() { return rule; }
		
		//A1 | A2 | B1 | B2 | C1 | C2
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//A1
		public EnumLiteralDeclaration getA1EnumLiteralDeclaration_0() { return cA1EnumLiteralDeclaration_0; }
		
		public Keyword getA1A1Keyword_0_0() { return cA1A1Keyword_0_0; }
		
		//A2
		public EnumLiteralDeclaration getA2EnumLiteralDeclaration_1() { return cA2EnumLiteralDeclaration_1; }
		
		public Keyword getA2A2Keyword_1_0() { return cA2A2Keyword_1_0; }
		
		//B1
		public EnumLiteralDeclaration getB1EnumLiteralDeclaration_2() { return cB1EnumLiteralDeclaration_2; }
		
		public Keyword getB1B1Keyword_2_0() { return cB1B1Keyword_2_0; }
		
		//B2
		public EnumLiteralDeclaration getB2EnumLiteralDeclaration_3() { return cB2EnumLiteralDeclaration_3; }
		
		public Keyword getB2B2Keyword_3_0() { return cB2B2Keyword_3_0; }
		
		//C1
		public EnumLiteralDeclaration getC1EnumLiteralDeclaration_4() { return cC1EnumLiteralDeclaration_4; }
		
		public Keyword getC1C1Keyword_4_0() { return cC1C1Keyword_4_0; }
		
		//C2
		public EnumLiteralDeclaration getC2EnumLiteralDeclaration_5() { return cC2EnumLiteralDeclaration_5; }
		
		public Keyword getC2C2Keyword_5_0() { return cC2C2Keyword_5_0; }
	}
	public class PartnerTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.PartnerType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cIndustrialEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cIndustrialIndustrialKeyword_0_0 = (Keyword)cIndustrialEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAcademicEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAcademicAcademicKeyword_1_0 = (Keyword)cAcademicEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum PartnerType returns PartnerType:
		//  Industrial | Academic;
		public EnumRule getRule() { return rule; }
		
		//Industrial | Academic
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Industrial
		public EnumLiteralDeclaration getIndustrialEnumLiteralDeclaration_0() { return cIndustrialEnumLiteralDeclaration_0; }
		
		public Keyword getIndustrialIndustrialKeyword_0_0() { return cIndustrialIndustrialKeyword_0_0; }
		
		//Academic
		public EnumLiteralDeclaration getAcademicEnumLiteralDeclaration_1() { return cAcademicEnumLiteralDeclaration_1; }
		
		public Keyword getAcademicAcademicKeyword_1_0() { return cAcademicAcademicKeyword_1_0; }
	}
	public class DegreeLevelElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.DegreeLevel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBachelorEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBachelorBachelorKeyword_0_0 = (Keyword)cBachelorEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMasterEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMasterMasterKeyword_1_0 = (Keyword)cMasterEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum DegreeLevel returns DegreeLevel:
		//  Bachelor | Master;
		public EnumRule getRule() { return rule; }
		
		//Bachelor | Master
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Bachelor
		public EnumLiteralDeclaration getBachelorEnumLiteralDeclaration_0() { return cBachelorEnumLiteralDeclaration_0; }
		
		public Keyword getBachelorBachelorKeyword_0_0() { return cBachelorBachelorKeyword_0_0; }
		
		//Master
		public EnumLiteralDeclaration getMasterEnumLiteralDeclaration_1() { return cMasterEnumLiteralDeclaration_1; }
		
		public Keyword getMasterMasterKeyword_1_0() { return cMasterMasterKeyword_1_0; }
	}
	
	private final ErasmusProgramElements pErasmusProgram;
	private final ScholarshipElements pScholarship;
	private final UniversityElements pUniversity;
	private final CourseElements pCourse;
	private final LocationElements pLocation;
	private final AssociatePartnerElements pAssociatePartner;
	private final AdmissionStructureElements pAdmissionStructure;
	private final ResultsElements pResults;
	private final RequirementElements pRequirement;
	private final DocumentRequirementElements pDocumentRequirement;
	private final DegreeRequirementElements pDegreeRequirement;
	private final LanguageRequirementElements pLanguageRequirement;
	private final ApplicationProcessElements pApplicationProcess;
	private final StepElements pStep;
	private final TerminalRule tEDATE;
	private final ScholarshipTypeElements eScholarshipType;
	private final LanguageLevelElements eLanguageLevel;
	private final PartnerTypeElements ePartnerType;
	private final DegreeLevelElements eDegreeLevel;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ErasmusProgramsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pErasmusProgram = new ErasmusProgramElements();
		this.pScholarship = new ScholarshipElements();
		this.pUniversity = new UniversityElements();
		this.pCourse = new CourseElements();
		this.pLocation = new LocationElements();
		this.pAssociatePartner = new AssociatePartnerElements();
		this.pAdmissionStructure = new AdmissionStructureElements();
		this.pResults = new ResultsElements();
		this.pRequirement = new RequirementElements();
		this.pDocumentRequirement = new DocumentRequirementElements();
		this.pDegreeRequirement = new DegreeRequirementElements();
		this.pLanguageRequirement = new LanguageRequirementElements();
		this.pApplicationProcess = new ApplicationProcessElements();
		this.pStep = new StepElements();
		this.tEDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mde.a5.ErasmusPrograms.EDATE");
		this.eScholarshipType = new ScholarshipTypeElements();
		this.eLanguageLevel = new LanguageLevelElements();
		this.ePartnerType = new PartnerTypeElements();
		this.eDegreeLevel = new DegreeLevelElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.mde.a5.ErasmusPrograms".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////generate erasmusPrograms "http://www.xtext.org/mde/a5/ErasmusPrograms"
	//ErasmusProgram returns ErasmusProgram:
	//  'ErasmusProgram' name=STRING '{'
	//    'totalCredits' totalCredits=INT
	//    ('universities' '{' universities+=University (',' universities+=University)* '}' )?
	//    ('scholarships' '{' scholarships+=Scholarship (',' scholarships+=Scholarship)* '}' )?
	//    ('associatePartners' '{' associatePartners+=AssociatePartner (',' associatePartners+=AssociatePartner)* '}' )?
	//    'admissionStructure' admissionStructure=AdmissionStructure
	//  '}';
	public ErasmusProgramElements getErasmusProgramAccess() {
		return pErasmusProgram;
	}
	
	public ParserRule getErasmusProgramRule() {
		return getErasmusProgramAccess().getRule();
	}
	
	//Scholarship returns Scholarship:
	//  type=ScholarshipType '{'
	//    'tuitionFee' tuitionFee=INT
	//    'travelGrant' travelGrant=INT
	//    'allowance' allowance=INT
	//  '}';
	public ScholarshipElements getScholarshipAccess() {
		return pScholarship;
	}
	
	public ParserRule getScholarshipRule() {
		return getScholarshipAccess().getRule();
	}
	
	//University returns University:
	//  'University' universityName=STRING '{'
	//    'location' location=Location
	//    'credits' credits=INT
	//    ('courses' '{' courses+=Course (',' courses+=Course)* '}' )?
	//  '}';
	public UniversityElements getUniversityAccess() {
		return pUniversity;
	}
	
	public ParserRule getUniversityRule() {
		return getUniversityAccess().getRule();
	}
	
	//Course returns Course:
	//  '{'
	//    'code' ':' courseCode=STRING
	//    'name' ':' courseName=STRING
	//    'faculty' ':' faculty=STRING
	//    'credits' ':' courseCredits=INT
	//  '}';
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//Location returns Location:
	//  '{'
	//    'country' ':' countryName=STRING
	//    'city' ':' cityName=STRING
	//  '}';
	public LocationElements getLocationAccess() {
		return pLocation;
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}
	
	//AssociatePartner returns AssociatePartner:
	//    partnerName=STRING '(' type=PartnerType ')';
	public AssociatePartnerElements getAssociatePartnerAccess() {
		return pAssociatePartner;
	}
	
	public ParserRule getAssociatePartnerRule() {
		return getAssociatePartnerAccess().getRule();
	}
	
	//AdmissionStructure returns AdmissionStructure:
	//  '{'
	//    'applicationProcess' applicationProcess=ApplicationProcess
	//    ('requirements' '{' requierements+=Requirement (',' requierements+=Requirement)* '}' )?
	//    ('results' '{' results+=Results (',' results+=Results)* '}' )?
	//  '}';
	public AdmissionStructureElements getAdmissionStructureAccess() {
		return pAdmissionStructure;
	}
	
	public ParserRule getAdmissionStructureRule() {
		return getAdmissionStructureAccess().getRule();
	}
	
	//Results returns Results:
	//  'Year' year=INT '{'
	//    'totalAdmitted' totalAdmitted=INT
	//    'scholarshipsAwarded' scholarshipsAwarded=INT
	//    ('admittedStudents' '{' admittedStudents+=STRING (',' admittedStudents+=STRING)* '}' )?
	//  '}';
	public ResultsElements getResultsAccess() {
		return pResults;
	}
	
	public ParserRule getResultsRule() {
		return getResultsAccess().getRule();
	}
	
	//Requirement returns Requirement:
	//  DocumentRequirement | DegreeRequirement | LanguageRequirement;
	public RequirementElements getRequirementAccess() {
		return pRequirement;
	}
	
	public ParserRule getRequirementRule() {
		return getRequirementAccess().getRule();
	}
	
	//DocumentRequirement returns DocumentRequirement:
	//  'DocumentRequirement' '{'
	//    'documentName' documentName=STRING
	//    'description' description=STRING
	//  '}';
	public DocumentRequirementElements getDocumentRequirementAccess() {
		return pDocumentRequirement;
	}
	
	public ParserRule getDocumentRequirementRule() {
		return getDocumentRequirementAccess().getRule();
	}
	
	//DegreeRequirement returns DegreeRequirement:
	//  'DegreeRequirement' '{'
	//    'degreeName' degreeName=STRING
	//    'fieldOfStudy' fieldOfStudy=STRING
	//    'level' level=DegreeLevel
	//  '}';
	public DegreeRequirementElements getDegreeRequirementAccess() {
		return pDegreeRequirement;
	}
	
	public ParserRule getDegreeRequirementRule() {
		return getDegreeRequirementAccess().getRule();
	}
	
	//LanguageRequirement returns LanguageRequirement:
	//  'LanguageRequirement' '{'
	//    'language' languageName=STRING
	//    'level' level=LanguageLevel
	//  '}';
	public LanguageRequirementElements getLanguageRequirementAccess() {
		return pLanguageRequirement;
	}
	
	public ParserRule getLanguageRequirementRule() {
		return getLanguageRequirementAccess().getRule();
	}
	
	//ApplicationProcess returns ApplicationProcess:
	//  {ApplicationProcess} '{'
	//    ('steps' '{' steps+=Step (',' steps+=Step)* '}' )?
	//  '}';
	public ApplicationProcessElements getApplicationProcessAccess() {
		return pApplicationProcess;
	}
	
	public ParserRule getApplicationProcessRule() {
		return getApplicationProcessAccess().getRule();
	}
	
	//Step returns Step:
	//  'Step' stepName=STRING '{'
	//    'description' stepDescription=STRING
	//    'startDate' startDate=EDATE
	//    'endDate' endDate=EDATE
	//  '}';
	public StepElements getStepAccess() {
		return pStep;
	}
	
	public ParserRule getStepRule() {
		return getStepAccess().getRule();
	}
	
	//// Define EDATE as a data type
	//// rule copied from https://www.eclipse.org/forums/index.php?t=msg&th=1071390&goto=1712637&#msg_1712637
	//terminal EDATE returns ecore::EDate:
	//  '0'..'9''0'..'9''0'..'9''0'..'9' '-' '0'..'9''0'..'9' '-' '0'..'9''0'..'9';
	public TerminalRule getEDATERule() {
		return tEDATE;
	}
	
	//// Enums
	//enum ScholarshipType returns ScholarshipType:
	//  Program_Country | Partner_Country;
	public ScholarshipTypeElements getScholarshipTypeAccess() {
		return eScholarshipType;
	}
	
	public EnumRule getScholarshipTypeRule() {
		return getScholarshipTypeAccess().getRule();
	}
	
	//enum LanguageLevel returns LanguageLevel:
	//  A1 | A2 | B1 | B2 | C1 | C2;
	public LanguageLevelElements getLanguageLevelAccess() {
		return eLanguageLevel;
	}
	
	public EnumRule getLanguageLevelRule() {
		return getLanguageLevelAccess().getRule();
	}
	
	//enum PartnerType returns PartnerType:
	//  Industrial | Academic;
	public PartnerTypeElements getPartnerTypeAccess() {
		return ePartnerType;
	}
	
	public EnumRule getPartnerTypeRule() {
		return getPartnerTypeAccess().getRule();
	}
	
	//enum DegreeLevel returns DegreeLevel:
	//  Bachelor | Master;
	public DegreeLevelElements getDegreeLevelAccess() {
		return eDegreeLevel;
	}
	
	public EnumRule getDegreeLevelRule() {
		return getDegreeLevelAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
