package ErasmusPrograms.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_LanguageLevel extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LanguageLevel() {
    super(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695efL, "LanguageLevel", "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158383");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_A1_0 = new EnumerationDescriptor.MemberDescriptor("A1", "a1", 0x26276edc561695f0L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158384");
  private final EnumerationDescriptor.MemberDescriptor myMember_A2_0 = new EnumerationDescriptor.MemberDescriptor("A2", "a2", 0x26276edc561695f1L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158385");
  private final EnumerationDescriptor.MemberDescriptor myMember_B1_0 = new EnumerationDescriptor.MemberDescriptor("B1", "b1", 0x26276edc561695f4L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158388");
  private final EnumerationDescriptor.MemberDescriptor myMember_B2_0 = new EnumerationDescriptor.MemberDescriptor("B2", "b2", 0x26276edc561695f8L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158392");
  private final EnumerationDescriptor.MemberDescriptor myMember_C1_0 = new EnumerationDescriptor.MemberDescriptor("C1", "c1", 0x26276edc561695fdL, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158397");
  private final EnumerationDescriptor.MemberDescriptor myMember_C2_0 = new EnumerationDescriptor.MemberDescriptor("C2", "c2", 0x26276edc56169603L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158403");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695efL, 0x26276edc561695f0L, 0x26276edc561695f1L, 0x26276edc561695f4L, 0x26276edc561695f8L, 0x26276edc561695fdL, 0x26276edc56169603L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_A1_0, myMember_A2_0, myMember_B1_0, myMember_B2_0, myMember_C1_0, myMember_C2_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "A1":
        return myMember_A1_0;
      case "A2":
        return myMember_A2_0;
      case "B1":
        return myMember_B1_0;
      case "B2":
        return myMember_B2_0;
      case "C1":
        return myMember_C1_0;
      case "C2":
        return myMember_C2_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
