package ErasmusPrograms.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PartnerType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PartnerType() {
    super(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e4eL, "PartnerType", "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148238");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_INDUSTRIAL_0 = new EnumerationDescriptor.MemberDescriptor("INDUSTRIAL", "industrial", 0x26276edc56166e4fL, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148239");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACADEMIC_0 = new EnumerationDescriptor.MemberDescriptor("ACADEMIC", "academic", 0x26276edc56166e50L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148240");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e4eL, 0x26276edc56166e4fL, 0x26276edc56166e50L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_INDUSTRIAL_0, myMember_ACADEMIC_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "INDUSTRIAL":
        return myMember_INDUSTRIAL_0;
      case "ACADEMIC":
        return myMember_ACADEMIC_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
