package ErasmusPrograms.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ScholarshipType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ScholarshipType() {
    super(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e18L, "ScholarshipType", "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148184");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PROGRAMCOUNTRY_0 = new EnumerationDescriptor.MemberDescriptor("PROGRAMCOUNTRY", "programCountry", 0x26276edc56166e19L, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148185");
  private final EnumerationDescriptor.MemberDescriptor myMember_PARTNERCOUNTRY_0 = new EnumerationDescriptor.MemberDescriptor("PARTNERCOUNTRY", "partnerCountry", 0x26276edc56166e1bL, "r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148187");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e18L, 0x26276edc56166e19L, 0x26276edc56166e1bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PROGRAMCOUNTRY_0, myMember_PARTNERCOUNTRY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PROGRAMCOUNTRY":
        return myMember_PROGRAMCOUNTRY_0;
      case "PARTNERCOUNTRY":
        return myMember_PARTNERCOUNTRY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
