package ErasmusPrograms.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAdmissionStructure = createDescriptorForAdmissionStructure();
  /*package*/ final ConceptDescriptor myConceptApplicationProcess = createDescriptorForApplicationProcess();
  /*package*/ final ConceptDescriptor myConceptAssociatePartner = createDescriptorForAssociatePartner();
  /*package*/ final ConceptDescriptor myConceptCourse = createDescriptorForCourse();
  /*package*/ final ConceptDescriptor myConceptDegreeRequirement = createDescriptorForDegreeRequirement();
  /*package*/ final ConceptDescriptor myConceptDocumentRequirement = createDescriptorForDocumentRequirement();
  /*package*/ final ConceptDescriptor myConceptErasmusProgram = createDescriptorForErasmusProgram();
  /*package*/ final ConceptDescriptor myConceptLanguageRequirement = createDescriptorForLanguageRequirement();
  /*package*/ final ConceptDescriptor myConceptLocation = createDescriptorForLocation();
  /*package*/ final ConceptDescriptor myConceptRequirement = createDescriptorForRequirement();
  /*package*/ final ConceptDescriptor myConceptResults = createDescriptorForResults();
  /*package*/ final ConceptDescriptor myConceptScholarship = createDescriptorForScholarship();
  /*package*/ final ConceptDescriptor myConceptStep = createDescriptorForStep();
  /*package*/ final ConceptDescriptor myConceptUniversity = createDescriptorForUniversity();
  /*package*/ final EnumerationDescriptor myEnumerationDegreeLevel = new EnumerationDescriptor_DegreeLevel();
  /*package*/ final EnumerationDescriptor myEnumerationLanguageLevel = new EnumerationDescriptor_LanguageLevel();
  /*package*/ final EnumerationDescriptor myEnumerationPartnerType = new EnumerationDescriptor_PartnerType();
  /*package*/ final EnumerationDescriptor myEnumerationScholarshipType = new EnumerationDescriptor_ScholarshipType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAdmissionStructure, myConceptApplicationProcess, myConceptAssociatePartner, myConceptCourse, myConceptDegreeRequirement, myConceptDocumentRequirement, myConceptErasmusProgram, myConceptLanguageRequirement, myConceptLocation, myConceptRequirement, myConceptResults, myConceptScholarship, myConceptStep, myConceptUniversity);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AdmissionStructure:
        return myConceptAdmissionStructure;
      case LanguageConceptSwitch.ApplicationProcess:
        return myConceptApplicationProcess;
      case LanguageConceptSwitch.AssociatePartner:
        return myConceptAssociatePartner;
      case LanguageConceptSwitch.Course:
        return myConceptCourse;
      case LanguageConceptSwitch.DegreeRequirement:
        return myConceptDegreeRequirement;
      case LanguageConceptSwitch.DocumentRequirement:
        return myConceptDocumentRequirement;
      case LanguageConceptSwitch.ErasmusProgram:
        return myConceptErasmusProgram;
      case LanguageConceptSwitch.LanguageRequirement:
        return myConceptLanguageRequirement;
      case LanguageConceptSwitch.Location:
        return myConceptLocation;
      case LanguageConceptSwitch.Requirement:
        return myConceptRequirement;
      case LanguageConceptSwitch.Results:
        return myConceptResults;
      case LanguageConceptSwitch.Scholarship:
        return myConceptScholarship;
      case LanguageConceptSwitch.Step:
        return myConceptStep;
      case LanguageConceptSwitch.University:
        return myConceptUniversity;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationDegreeLevel, myEnumerationLanguageLevel, myEnumerationPartnerType, myEnumerationScholarshipType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAdmissionStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "AdmissionStructure", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e57L);
    b.class_(false, false, false);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148247");
    b.version(3);
    b.aggregate("requirements", 0x26276edc56169637L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL).optional(false).ordered(true).multiple(true).origin("2749287990149158455").done();
    b.aggregate("applicationProcess", 0x26276edc56169639L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695eeL).optional(false).ordered(true).multiple(true).origin("2749287990149158457").done();
    b.aggregate("results", 0x26276edc5616963cL).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e58L).optional(true).ordered(true).multiple(true).origin("2749287990149158460").done();
    b.alias("admission");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApplicationProcess() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "ApplicationProcess", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695eeL);
    b.class_(false, false, false);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158382");
    b.version(3);
    b.aggregate("steps", 0x26276edc56169640L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc5616960aL).optional(false).ordered(true).multiple(true).origin("2749287990149158464").done();
    b.alias("application process");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAssociatePartner() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "AssociatePartner", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e4bL);
    b.class_(false, false, false);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148235");
    b.version(3);
    b.property("name", 0x26276edc56166e4cL).type(PrimitiveTypeId.STRING).origin("2749287990149148236").done();
    b.property("type", 0x26276edc56166e54L).type(MetaIdFactory.dataTypeId(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e4eL)).origin("2749287990149148244").done();
    b.alias("partner");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCourse() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Course", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e35L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148213");
    b.version(3);
    b.property("courseCode", 0x26276edc56166e36L).type(PrimitiveTypeId.STRING).origin("2749287990149148214").done();
    b.property("credits", 0x26276edc56166e3bL).type(PrimitiveTypeId.INTEGER).origin("2749287990149148219").done();
    b.property("faculty", 0x26276edc56166e3fL).type(PrimitiveTypeId.STRING).origin("2749287990149148223").done();
    b.alias("course");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDegreeRequirement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "DegreeRequirement", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc5616961aL);
    b.class_(false, false, false);
    // extends: ErasmusPrograms.structure.Requirement
    b.super_(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158426");
    b.version(3);
    b.property("fieldOfStudy", 0x26276edc5616961dL).type(PrimitiveTypeId.STRING).origin("2749287990149158429").done();
    b.property("level", 0x26276edc56169620L).type(MetaIdFactory.dataTypeId(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695e7L)).origin("2749287990149158432").done();
    b.alias("degree requirement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDocumentRequirement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "DocumentRequirement", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695dbL);
    b.class_(false, false, false);
    // extends: ErasmusPrograms.structure.Requirement
    b.super_(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158363");
    b.version(3);
    b.property("description", 0x26276edc561695deL).type(PrimitiveTypeId.STRING).origin("2749287990149158366").done();
    b.alias("document requirement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForErasmusProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "ErasmusProgram", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x9d77ea4d04f30c3L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/709174712668729539");
    b.version(3);
    b.property("id", 0x26276edc5622410dL).type(PrimitiveTypeId.INTEGER).origin("2749287990149923085").done();
    b.property("totalCredits", 0x26276edc56166dfdL).type(PrimitiveTypeId.INTEGER).origin("2749287990149148157").done();
    b.aggregate("scholarships", 0x26276edc5616962eL).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e00L).optional(false).ordered(true).multiple(true).origin("2749287990149158446").done();
    b.aggregate("universities", 0x26276edc56169628L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e2eL).optional(false).ordered(true).multiple(true).origin("2749287990149158440").done();
    b.aggregate("associatePartner", 0x26276edc56169631L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e4bL).optional(true).ordered(true).multiple(true).origin("2749287990149158449").done();
    b.aggregate("admissionStructure", 0x74bd21fd9dff74d5L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e57L).optional(false).ordered(true).multiple(false).origin("8411917052159161557").done();
    b.alias("erasmus program");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLanguageRequirement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "LanguageRequirement", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695e1L);
    b.class_(false, false, false);
    // extends: ErasmusPrograms.structure.Requirement
    b.super_(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158369");
    b.version(3);
    b.property("level", 0x26276edc561695e4L).type(MetaIdFactory.dataTypeId(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc561695efL)).origin("2749287990149158372").done();
    b.alias("language requirement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Location", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e45L);
    b.class_(false, false, false);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148229");
    b.version(3);
    b.property("countryName", 0x26276edc56166e46L).type(PrimitiveTypeId.STRING).origin("2749287990149148230").done();
    b.property("cityName", 0x26276edc56166e48L).type(PrimitiveTypeId.STRING).origin("2749287990149148232").done();
    b.alias("location");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Requirement", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148266");
    b.version(3);
    b.alias("requirement");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForResults() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Results", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e58L);
    b.class_(false, false, false);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148248");
    b.version(3);
    b.property("year", 0x26276edc56166e59L).type(PrimitiveTypeId.INTEGER).origin("2749287990149148249").done();
    b.property("totalAdmitted", 0x26276edc56166e5bL).type(PrimitiveTypeId.INTEGER).origin("2749287990149148251").done();
    b.property("scholarshipsAwarded", 0x26276edc56166e5fL).type(PrimitiveTypeId.INTEGER).origin("2749287990149148255").done();
    b.property("admittedStudents", 0x26276edc56166e63L).type(PrimitiveTypeId.STRING).origin("2749287990149148259").done();
    b.alias("results");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScholarship() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Scholarship", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e00L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148160");
    b.version(3);
    b.property("type", 0x26276edc56166e02L).type(MetaIdFactory.dataTypeId(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e18L)).origin("2749287990149148162").done();
    b.property("tuitionFee", 0x26276edc56166e1fL).type(PrimitiveTypeId.INTEGER).origin("2749287990149148191").done();
    b.property("travelGrant", 0x26276edc56166e24L).type(PrimitiveTypeId.INTEGER).origin("2749287990149148196").done();
    b.property("allowance", 0x26276edc56166e28L).type(PrimitiveTypeId.INTEGER).origin("2749287990149148200").done();
    b.alias("scholarship");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStep() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "Step", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc5616960aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149158410");
    b.version(3);
    b.property("description", 0x26276edc5616960dL).type(PrimitiveTypeId.STRING).origin("2749287990149158413").done();
    b.property("startDate", 0x26276edc56169610L).type(PrimitiveTypeId.STRING).origin("2749287990149158416").done();
    b.property("endDate", 0x26276edc56169614L).type(PrimitiveTypeId.STRING).origin("2749287990149158420").done();
    b.alias("step");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUniversity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ErasmusPrograms", "University", 0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e2eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:40de22c9-4125-47c0-9445-9ee5570f6c96(ErasmusPrograms.structure)/2749287990149148206");
    b.version(3);
    b.property("credits", 0x26276edc56166e31L).type(PrimitiveTypeId.INTEGER).origin("2749287990149148209").done();
    b.aggregate("courses", 0x26276edc56169625L).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e35L).optional(false).ordered(true).multiple(true).origin("2749287990149158437").done();
    b.aggregate("location", 0x74bd21fd9dff74afL).target(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e45L).optional(false).ordered(true).multiple(false).origin("8411917052159161519").done();
    b.alias("university");
    return b.create();
  }
}
