/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.mde.a5.ide.contentassist.antlr.internal.InternalErasmusProgramsParser;
import org.xtext.mde.a5.services.ErasmusProgramsGrammarAccess;

public class ErasmusProgramsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ErasmusProgramsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ErasmusProgramsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRequirementAccess().getAlternatives(), "rule__Requirement__Alternatives");
			builder.put(grammarAccess.getScholarshipTypeAccess().getAlternatives(), "rule__ScholarshipType__Alternatives");
			builder.put(grammarAccess.getLanguageLevelAccess().getAlternatives(), "rule__LanguageLevel__Alternatives");
			builder.put(grammarAccess.getPartnerTypeAccess().getAlternatives(), "rule__PartnerType__Alternatives");
			builder.put(grammarAccess.getDegreeLevelAccess().getAlternatives(), "rule__DegreeLevel__Alternatives");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup(), "rule__ErasmusProgram__Group__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_5(), "rule__ErasmusProgram__Group_5__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_5_3(), "rule__ErasmusProgram__Group_5_3__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_6(), "rule__ErasmusProgram__Group_6__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_6_3(), "rule__ErasmusProgram__Group_6_3__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_7(), "rule__ErasmusProgram__Group_7__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getGroup_7_3(), "rule__ErasmusProgram__Group_7_3__0");
			builder.put(grammarAccess.getScholarshipAccess().getGroup(), "rule__Scholarship__Group__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup(), "rule__University__Group__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_7(), "rule__University__Group_7__0");
			builder.put(grammarAccess.getUniversityAccess().getGroup_7_3(), "rule__University__Group_7_3__0");
			builder.put(grammarAccess.getCourseAccess().getGroup(), "rule__Course__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getAssociatePartnerAccess().getGroup(), "rule__AssociatePartner__Group__0");
			builder.put(grammarAccess.getAdmissionStructureAccess().getGroup(), "rule__AdmissionStructure__Group__0");
			builder.put(grammarAccess.getAdmissionStructureAccess().getGroup_3(), "rule__AdmissionStructure__Group_3__0");
			builder.put(grammarAccess.getAdmissionStructureAccess().getGroup_3_3(), "rule__AdmissionStructure__Group_3_3__0");
			builder.put(grammarAccess.getAdmissionStructureAccess().getGroup_4(), "rule__AdmissionStructure__Group_4__0");
			builder.put(grammarAccess.getAdmissionStructureAccess().getGroup_4_3(), "rule__AdmissionStructure__Group_4_3__0");
			builder.put(grammarAccess.getResultsAccess().getGroup(), "rule__Results__Group__0");
			builder.put(grammarAccess.getResultsAccess().getGroup_7(), "rule__Results__Group_7__0");
			builder.put(grammarAccess.getResultsAccess().getGroup_7_3(), "rule__Results__Group_7_3__0");
			builder.put(grammarAccess.getDocumentRequirementAccess().getGroup(), "rule__DocumentRequirement__Group__0");
			builder.put(grammarAccess.getDegreeRequirementAccess().getGroup(), "rule__DegreeRequirement__Group__0");
			builder.put(grammarAccess.getLanguageRequirementAccess().getGroup(), "rule__LanguageRequirement__Group__0");
			builder.put(grammarAccess.getApplicationProcessAccess().getGroup(), "rule__ApplicationProcess__Group__0");
			builder.put(grammarAccess.getApplicationProcessAccess().getGroup_2(), "rule__ApplicationProcess__Group_2__0");
			builder.put(grammarAccess.getApplicationProcessAccess().getGroup_2_3(), "rule__ApplicationProcess__Group_2_3__0");
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getErasmusProgramAccess().getNameAssignment_1(), "rule__ErasmusProgram__NameAssignment_1");
			builder.put(grammarAccess.getErasmusProgramAccess().getTotalCreditsAssignment_4(), "rule__ErasmusProgram__TotalCreditsAssignment_4");
			builder.put(grammarAccess.getErasmusProgramAccess().getUniversitiesAssignment_5_2(), "rule__ErasmusProgram__UniversitiesAssignment_5_2");
			builder.put(grammarAccess.getErasmusProgramAccess().getUniversitiesAssignment_5_3_1(), "rule__ErasmusProgram__UniversitiesAssignment_5_3_1");
			builder.put(grammarAccess.getErasmusProgramAccess().getScholarshipsAssignment_6_2(), "rule__ErasmusProgram__ScholarshipsAssignment_6_2");
			builder.put(grammarAccess.getErasmusProgramAccess().getScholarshipsAssignment_6_3_1(), "rule__ErasmusProgram__ScholarshipsAssignment_6_3_1");
			builder.put(grammarAccess.getErasmusProgramAccess().getAssociatePartnersAssignment_7_2(), "rule__ErasmusProgram__AssociatePartnersAssignment_7_2");
			builder.put(grammarAccess.getErasmusProgramAccess().getAssociatePartnersAssignment_7_3_1(), "rule__ErasmusProgram__AssociatePartnersAssignment_7_3_1");
			builder.put(grammarAccess.getErasmusProgramAccess().getAdmissionStructureAssignment_9(), "rule__ErasmusProgram__AdmissionStructureAssignment_9");
			builder.put(grammarAccess.getScholarshipAccess().getTypeAssignment_0(), "rule__Scholarship__TypeAssignment_0");
			builder.put(grammarAccess.getScholarshipAccess().getTuitionFeeAssignment_3(), "rule__Scholarship__TuitionFeeAssignment_3");
			builder.put(grammarAccess.getScholarshipAccess().getTravelGrantAssignment_5(), "rule__Scholarship__TravelGrantAssignment_5");
			builder.put(grammarAccess.getScholarshipAccess().getAllowanceAssignment_7(), "rule__Scholarship__AllowanceAssignment_7");
			builder.put(grammarAccess.getUniversityAccess().getUniversityNameAssignment_1(), "rule__University__UniversityNameAssignment_1");
			builder.put(grammarAccess.getUniversityAccess().getLocationAssignment_4(), "rule__University__LocationAssignment_4");
			builder.put(grammarAccess.getUniversityAccess().getCreditsAssignment_6(), "rule__University__CreditsAssignment_6");
			builder.put(grammarAccess.getUniversityAccess().getCoursesAssignment_7_2(), "rule__University__CoursesAssignment_7_2");
			builder.put(grammarAccess.getUniversityAccess().getCoursesAssignment_7_3_1(), "rule__University__CoursesAssignment_7_3_1");
			builder.put(grammarAccess.getCourseAccess().getCourseCodeAssignment_3(), "rule__Course__CourseCodeAssignment_3");
			builder.put(grammarAccess.getCourseAccess().getCourseNameAssignment_6(), "rule__Course__CourseNameAssignment_6");
			builder.put(grammarAccess.getCourseAccess().getFacultyAssignment_9(), "rule__Course__FacultyAssignment_9");
			builder.put(grammarAccess.getCourseAccess().getCourseCreditsAssignment_12(), "rule__Course__CourseCreditsAssignment_12");
			builder.put(grammarAccess.getLocationAccess().getCountryNameAssignment_3(), "rule__Location__CountryNameAssignment_3");
			builder.put(grammarAccess.getLocationAccess().getCityNameAssignment_6(), "rule__Location__CityNameAssignment_6");
			builder.put(grammarAccess.getAssociatePartnerAccess().getPartnerNameAssignment_0(), "rule__AssociatePartner__PartnerNameAssignment_0");
			builder.put(grammarAccess.getAssociatePartnerAccess().getTypeAssignment_2(), "rule__AssociatePartner__TypeAssignment_2");
			builder.put(grammarAccess.getAdmissionStructureAccess().getApplicationProcessAssignment_2(), "rule__AdmissionStructure__ApplicationProcessAssignment_2");
			builder.put(grammarAccess.getAdmissionStructureAccess().getRequierementsAssignment_3_2(), "rule__AdmissionStructure__RequierementsAssignment_3_2");
			builder.put(grammarAccess.getAdmissionStructureAccess().getRequierementsAssignment_3_3_1(), "rule__AdmissionStructure__RequierementsAssignment_3_3_1");
			builder.put(grammarAccess.getAdmissionStructureAccess().getResultsAssignment_4_2(), "rule__AdmissionStructure__ResultsAssignment_4_2");
			builder.put(grammarAccess.getAdmissionStructureAccess().getResultsAssignment_4_3_1(), "rule__AdmissionStructure__ResultsAssignment_4_3_1");
			builder.put(grammarAccess.getResultsAccess().getYearAssignment_1(), "rule__Results__YearAssignment_1");
			builder.put(grammarAccess.getResultsAccess().getTotalAdmittedAssignment_4(), "rule__Results__TotalAdmittedAssignment_4");
			builder.put(grammarAccess.getResultsAccess().getScholarshipsAwardedAssignment_6(), "rule__Results__ScholarshipsAwardedAssignment_6");
			builder.put(grammarAccess.getResultsAccess().getAdmittedStudentsAssignment_7_2(), "rule__Results__AdmittedStudentsAssignment_7_2");
			builder.put(grammarAccess.getResultsAccess().getAdmittedStudentsAssignment_7_3_1(), "rule__Results__AdmittedStudentsAssignment_7_3_1");
			builder.put(grammarAccess.getDocumentRequirementAccess().getDocumentNameAssignment_3(), "rule__DocumentRequirement__DocumentNameAssignment_3");
			builder.put(grammarAccess.getDocumentRequirementAccess().getDescriptionAssignment_5(), "rule__DocumentRequirement__DescriptionAssignment_5");
			builder.put(grammarAccess.getDegreeRequirementAccess().getDegreeNameAssignment_3(), "rule__DegreeRequirement__DegreeNameAssignment_3");
			builder.put(grammarAccess.getDegreeRequirementAccess().getFieldOfStudyAssignment_5(), "rule__DegreeRequirement__FieldOfStudyAssignment_5");
			builder.put(grammarAccess.getDegreeRequirementAccess().getLevelAssignment_7(), "rule__DegreeRequirement__LevelAssignment_7");
			builder.put(grammarAccess.getLanguageRequirementAccess().getLanguageNameAssignment_3(), "rule__LanguageRequirement__LanguageNameAssignment_3");
			builder.put(grammarAccess.getLanguageRequirementAccess().getLevelAssignment_5(), "rule__LanguageRequirement__LevelAssignment_5");
			builder.put(grammarAccess.getApplicationProcessAccess().getStepsAssignment_2_2(), "rule__ApplicationProcess__StepsAssignment_2_2");
			builder.put(grammarAccess.getApplicationProcessAccess().getStepsAssignment_2_3_1(), "rule__ApplicationProcess__StepsAssignment_2_3_1");
			builder.put(grammarAccess.getStepAccess().getStepNameAssignment_1(), "rule__Step__StepNameAssignment_1");
			builder.put(grammarAccess.getStepAccess().getStepDescriptionAssignment_4(), "rule__Step__StepDescriptionAssignment_4");
			builder.put(grammarAccess.getStepAccess().getStartDateAssignment_6(), "rule__Step__StartDateAssignment_6");
			builder.put(grammarAccess.getStepAccess().getEndDateAssignment_8(), "rule__Step__EndDateAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ErasmusProgramsGrammarAccess grammarAccess;

	@Override
	protected InternalErasmusProgramsParser createParser() {
		InternalErasmusProgramsParser result = new InternalErasmusProgramsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ErasmusProgramsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ErasmusProgramsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
