/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.mde.a5.ui.internal.A5Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ErasmusProgramsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(A5Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		A5Activator activator = A5Activator.getInstance();
		return activator != null ? activator.getInjector(A5Activator.ORG_XTEXT_MDE_A5_ERASMUSPROGRAMS) : null;
	}

}
