/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractErasmusProgramsScopeProvider extends DelegatingScopeProvider {
}
