/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.ide;


/**
 * Use this class to register ide components.
 */
public class ErasmusProgramsIdeModule extends AbstractErasmusProgramsIdeModule {
}
