package ErasmusPrograms.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AdmissionStructure_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.results$BZmL)) {
      tgs.appendNode(item);
    }
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.applicationProcess$BTIp)) {
      tgs.appendNode(item);
    }
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.requirements$BTgn)) {
      tgs.appendNode(item);
    }
    tgs.newLine();

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink results$BZmL = MetaAdapterFactory.getContainmentLink(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e57L, 0x26276edc5616963cL, "results");
    /*package*/ static final SContainmentLink applicationProcess$BTIp = MetaAdapterFactory.getContainmentLink(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e57L, 0x26276edc56169639L, "applicationProcess");
    /*package*/ static final SContainmentLink requirements$BTgn = MetaAdapterFactory.getContainmentLink(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e57L, 0x26276edc56169637L, "requirements");
  }
}
