package ErasmusPrograms.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ErasmusProgram_Constraints extends BaseConstraintsDescriptor {
  public ErasmusProgram_Constraints() {
    super(CONCEPTS.ErasmusProgram$Le);
  }

  public static class TotalCredits_Property extends BasePropertyConstraintsDescriptor {
    public TotalCredits_Property(ConstraintsDescriptor container) {
      super(PROPS.totalCredits$ZklR, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:d62249e9-1888-40f9-9c51-bbbb092b81e0(ErasmusPrograms.constraints)", "2749287990149573068"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue == 60 || propertyValue == 90 || propertyValue == 120;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.totalCredits$ZklR, new TotalCredits_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ErasmusProgram$Le = MetaAdapterFactory.getConcept(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x9d77ea4d04f30c3L, "ErasmusPrograms.structure.ErasmusProgram");
  }

  private static final class PROPS {
    /*package*/ static final SProperty totalCredits$ZklR = MetaAdapterFactory.getProperty(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x9d77ea4d04f30c3L, 0x26276edc56166dfdL, "totalCredits");
  }
}
