package ErasmusPrograms.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Requirement_Constraints extends BaseConstraintsDescriptor {
  public Requirement_Constraints() {
    super(CONCEPTS.Requirement$wf);
  }

  @Override
  public SConcept getDefaultConcreteConcept() {
    return CONCEPTS.DegreeRequirement$DC;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Requirement$wf = MetaAdapterFactory.getConcept(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc56166e6aL, "ErasmusPrograms.structure.Requirement");
    /*package*/ static final SConcept DegreeRequirement$DC = MetaAdapterFactory.getConcept(0x45d743938b794afaL, 0x9cc9d68d79ce89e1L, 0x26276edc5616961aL, "ErasmusPrograms.structure.DegreeRequirement");
  }
}
