/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ErasmusProgramsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/mde/a5/parser/antlr/internal/InternalErasmusPrograms.tokens");
	}
}
