/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mde.a5.parser.antlr.internal.InternalErasmusProgramsParser;
import org.xtext.mde.a5.services.ErasmusProgramsGrammarAccess;

public class ErasmusProgramsParser extends AbstractAntlrParser {

	@Inject
	private ErasmusProgramsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalErasmusProgramsParser createParser(XtextTokenStream stream) {
		return new InternalErasmusProgramsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ErasmusProgram";
	}

	public ErasmusProgramsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ErasmusProgramsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
