/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ErasmusProgramsRuntimeModule extends AbstractErasmusProgramsRuntimeModule {
}
