/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mde.a5.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ErasmusProgramsUiModule extends AbstractErasmusProgramsUiModule {

	public ErasmusProgramsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
